;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-or-skip-quote
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        isearch-forward-regexp
        isearch-printing-char
        smex
        ))
