;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        evil-append
        evil-backward-char
        evil-backward-word-begin
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        erc-button-click-button
        evil-append-line
        evil-delete-backward-char-and-join
        haskell-indentation-delete-backward-char
        ido-switch-buffer
        isearch-forward-regexp
        isearch-printing-char
        mouse-save-then-kill
        nxml-electric-slash
        org-self-insert-command
        smex
        ))
